import 'package:adhd_assistant/secrets.dart';
import 'package:adhd_assistant/services/day_planner_service.dart';
import 'package:adhd_assistant/services/one_drive_sync_service.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  DayPlannerEntry entry({
    String type = 'task',
    String? subtitle,
    bool isAllDay = false,
    bool isConcurrent = false,
  }) {
    return DayPlannerEntry(
      id: 'entry-1',
      title: 'Entry',
      type: type,
      start: DateTime(2026, 8, 25, 9),
      end: DateTime(2026, 8, 25, 10),
      subtitle: subtitle,
      isAllDay: isAllDay,
      isConcurrent: isConcurrent,
    );
  }

  test('exports work and planner entries but skips imported home events', () {
    expect(
      OneDriveSyncService.isPlannerEntryExportable(
        entry(type: 'calendar', subtitle: 'Home calendar'),
      ),
      isFalse,
    );
    expect(
      OneDriveSyncService.isPlannerEntryExportable(
        entry(type: 'calendar', subtitle: 'Work calendar'),
      ),
      isFalse,
    );
    expect(
      OneDriveSyncService.isPlannerEntryExportable(
        entry(subtitle: 'Planner block', isAllDay: true),
      ),
      isFalse,
    );
    expect(
      OneDriveSyncService.isPlannerEntryExportable(
        entry(subtitle: 'Planner block', isConcurrent: true),
      ),
      isTrue,
    );
  });

  test('recognizes exported planner events by their body marker', () {
    expect(
      OneDriveSyncService.isPlannerGeneratedCalendarEvent({
        'body': {
          'content':
              'adhd-assistant-planner:entry-1\nGenerated by ADHD Assistant.',
        },
      }),
      isTrue,
    );
    expect(
      OneDriveSyncService.isPlannerGeneratedCalendarEvent({
        'body': {'content': 'A normal personal calendar event'},
      }),
      isFalse,
    );
  });

  test('recognizes legacy planner events by their old category', () {
    expect(
      OneDriveSyncService.isLegacyPlannerCalendarEvent({
        'categories': ['ADHD Assistant'],
      }),
      isTrue,
    );
    expect(
      OneDriveSyncService.isLegacyPlannerCalendarEvent({
        'categories': ['Work'],
      }),
      isFalse,
    );
  });

  test('work diary export selects only imported work calendar events', () {
    final events = [
      OutlookCalendarEvent(
        id: 'work-1',
        subject: 'Work meeting',
        start: DateTime(2026, 8, 25, 9),
        end: DateTime(2026, 8, 25, 10),
        isAllDay: false,
        calendarSource: 'work',
      ),
      OutlookCalendarEvent(
        id: 'home-1',
        subject: 'Personal appointment',
        start: DateTime(2026, 8, 25, 11),
        end: DateTime(2026, 8, 25, 12),
        isAllDay: false,
        calendarSource: 'home',
      ),
    ];

    expect(
      OneDriveSyncService.workCalendarEventsToExport(
        events,
      ).map((event) => event.id),
      ['work-1'],
    );
  });

  test('buildAuthorizationUrl includes the required OAuth parameters', () {
    const redirectUri = 'https://example.com/auth/callback';

    final authUrl = OneDriveSyncService.buildAuthorizationUrl(
      redirectUri: redirectUri,
      codeVerifier: 'test-verifier',
    );

    final uri = Uri.parse(authUrl);

    expect(uri.scheme, 'https');
    expect(uri.host, 'login.microsoftonline.com');
    expect(uri.path, '/consumers/oauth2/v2.0/authorize');
    expect(uri.queryParameters['client_id'], oneDriveClientId);
    expect(uri.queryParameters['response_type'], 'code');
    expect(uri.queryParameters['redirect_uri'], redirectUri);
    expect(uri.queryParameters['scope'], contains('Calendars.Read'));
    expect(uri.queryParameters['code_challenge_method'], 'S256');
    expect(uri.queryParameters['code_challenge'], isNotEmpty);
    expect(uri.queryParameters['state'], isNotEmpty);
  });
}
